#!/usr/bin/env python3
"""Claude Code `SessionEnd` hook — capture what a working session learned.

Wire it up (see `ops/daily/README.md`) and every session you finish is journalled into Ecphoria
and distilled into durable facts, so the next session starts already knowing what the last one
worked out.

Reads the hook payload from **stdin** (Claude Code passes hook data as JSON on stdin, not as
environment variables):

    {"session_id": "...", "transcript_path": "...", "cwd": "...",
     "hook_event_name": "SessionEnd", "reason": "clear|logout|other"}

What it stores, and what it deliberately does not:

* **Your prompts and the assistant's prose replies** — the reasoning and the decisions.
* **Not tool calls, tool results, file contents or diffs.** They dominate a transcript by volume
  (measured: 99% of it), are already in git, and would bury the signal under a corpus of the
  assistant's own outputs.
* **Not subagent chatter** (`isSidechain`) or system-injected turns (`isMeta`).
* **Not slash-command wrappers or interstitial narration.** "Let me check the config" is scaffolding
  between tool calls, not something to remember.

By default it **journals the turns and stops there**. The journal is immediately useful — SQL over
`episodic`, `GET /sessions/{id}/recall` to replay a past session — and it costs nothing.

Distillation into durable facts is opt-in (`ECPHORIA_CAPTURE_DISTILL=1`) because it needs a
completion provider on the server. Without one, `/sessions/{id}/distill` falls back to
concatenating the raw events into a single memory: ~15 KB of JSON that pollutes the corpus and
answers nothing. Better to journal and let the facts be written deliberately (`add_memory` /
`remember` over MCP) than to fill the store with dumps.

Failure is always silent-and-zero-exit: a memory server that is down must never break the exit of
an editing session.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request

URL = os.environ.get("ECPHORIA_URL", "http://localhost:8432").rstrip("/")
API_KEY = os.environ.get("ECPHORIA_API_KEY", "")
# Sessions shorter than this are almost always a quick question, not something worth remembering.
MIN_TURNS = int(os.environ.get("ECPHORIA_CAPTURE_MIN_TURNS", "4"))
# One turn's text, truncated. Long pasted logs add tokens, not meaning.
MAX_CHARS = int(os.environ.get("ECPHORIA_CAPTURE_MAX_CHARS", "4000"))
# Assistant turns shorter than this are the narration between tool calls ("Let me check X"), not
# an explanation worth keeping. User turns are kept regardless — a short question still frames
# what the session was about.
MIN_ASSISTANT_CHARS = int(os.environ.get("ECPHORIA_CAPTURE_MIN_ASSISTANT_CHARS", "280"))
# Distil the journalled session into facts. Needs a completion provider on the server — see the
# module docstring for why this is off by default.
DISTILL = os.environ.get("ECPHORIA_CAPTURE_DISTILL", "").lower() in ("1", "true", "yes")
TIMEOUT = 10


def post(path: str, body: dict) -> dict | None:
    req = urllib.request.Request(
        f"{URL}{path}",
        data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    if API_KEY:
        req.add_header("Authorization", f"Bearer {API_KEY}")
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return json.loads(resp.read() or b"{}")
    except (urllib.error.URLError, OSError, json.JSONDecodeError, TimeoutError):
        return None


# Wrappers the CLI injects around slash commands and local shell output. Their contents are
# machinery, not conversation.
NOISE_MARKERS = (
    "<command-name>",
    "<local-command-stdout>",
    "<system-reminder>",
    "Caveat: The messages below were generated by the user while running local commands",
)


def is_noise(text: str) -> bool:
    head = text.lstrip()[:400]
    return any(marker in head for marker in NOISE_MARKERS)


def text_of(message: dict) -> str:
    """Plain prose from an Anthropic message, dropping tool blocks."""
    content = message.get("content")
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return ""
    parts = [
        b.get("text", "")
        for b in content
        if isinstance(b, dict) and b.get("type") == "text"
    ]
    return "\n".join(p for p in parts if p).strip()


def read_turns(path: str) -> list[dict]:
    """Extract the human-readable conversation from a transcript."""
    turns: list[dict] = []
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if entry.get("type") not in ("user", "assistant"):
                    continue
                # Subagent transcripts and system-injected turns are not the conversation.
                if entry.get("isSidechain") or entry.get("isMeta"):
                    continue
                body = text_of(entry.get("message") or {})
                if not body or is_noise(body):
                    continue
                if entry["type"] == "assistant" and len(body) < MIN_ASSISTANT_CHARS:
                    continue
                turns.append(
                    {
                        "role": entry["type"],
                        "text": body[:MAX_CHARS],
                        "timestamp": entry.get("timestamp"),
                        "branch": entry.get("gitBranch"),
                    }
                )
    except OSError:
        return []
    return turns


def main() -> int:
    try:
        hook = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0

    session_id = hook.get("session_id")
    transcript = hook.get("transcript_path")
    if not session_id or not transcript:
        return 0

    turns = read_turns(transcript)
    if len(turns) < MIN_TURNS:
        return 0

    project = os.path.basename(hook.get("cwd") or os.getcwd())
    branch = next((t["branch"] for t in reversed(turns) if t.get("branch")), None)

    # Journal the conversation as episodic events tagged with the session, which is what
    # `/sessions/{id}/distill` reads. Episodic is the right home for the raw turns: queryable in
    # SQL, and not competing with the documentation corpus in memory search.
    events = [
        {
            "event_type": f"session.{t['role']}",
            "_session_id": session_id,
            "project": project,
            "branch": branch,
            "text": t["text"],
        }
        for t in turns
    ]
    if post("/api/v1/ingest", {"source": f"claude-code/{project}", "events": events}) is None:
        return 0

    distilled = 0
    if DISTILL:
        result = post(f"/api/v1/sessions/{session_id}/distill", {})
        # The endpoint returns one entry per distilled fact.
        if isinstance(result, list):
            distilled = len(result)
        elif isinstance(result, dict):
            distilled = result.get("distilled") or len(result.get("memories") or [])

    suffix = f", distilled {distilled}" if DISTILL else ""
    print(
        f"ecphoria: journalled {len(turns)} turns from {project}{suffix}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
